MEADE_COMMAND_SET = {
    "GetCurrentRA": {
        "description": "Gets the current Right Ascension.",
        "command": ":GR#",
        "parameter": None,
        "return": "{0:2d}:{1:2d}:{2:2d}#",
    },
    "GetCurrentDeclination": {
        "description": "Gets the current Declination.",
        "command": ":GD#",
        "parameter": None,
        "return": "{0:1s}{1:2d}*{2:2d}#",
    },
    "GetCurrentAltitude": {
        "description": "Gets the current Altitude.",
        "command": ":GA#",
        "parameter": None,
        "return": "{0:1s}{1:2d}*{2:2d}#",
    },
    "GetCurrentAzimuth": {
        "description": "Gets the current Azimuth.",
        "command": ":GZ#",
        "parameter": None,
        "return": "{0:3d}*{1:2d}#",
    },
    "GetCurrentSiderealTime": {
        "description": "Gets the current sidereal time.",
        "command": ":GS#",
        "parameter": None,
        "return": "{0:2d}:{1:2d}:{2:2d}#",
    },
    "SetSiderealTime": {
        "description": "Sets the sidereal time.",
        "command": ":SS",
        "parameter": "{0:2d}:{1:2d}:{2:2d}#",
        "return": "{0:1d}#",
    },
    "GetLocalTime": {
        "description": "Gets the local time.",
        "command": ":GL#",
        "parameter": None,
        "return": "{0:2d}:{1:2d}:{2:2d}#",
    },
    "SetLocalTime": {
        "description": "Sets the local time.",
        "command": ":SL",
        "parameter": "{0:2d}:{1:2d}:{2:2d}#",
        "return": "{0:1d}#",
    },
    "GetCalenderDate": {
        "description": "Gets the calendar date.",
        "command": ":GC#",
        "parameter": None,
        "return": "{0:2d}/{1:2d}/{2:2d}#",
    },
    "SetCalenderDate": {
        "description": "Sets the calendar date.",
        "command": ":SC",
        "parameter": "{0:2d}/{1:2d}/{2:2d}#",
        "return": "{0:1d}#",
    },
    "GetLatitude": {
        "description": "Gets the latitude of the currently selected site.",
        "command": ":Gt#",
        "parameter": None,
        "return": "{0:1s}{1:2d}*{2:2d}#",
    },
    "SetLatitude": {
        "description": "Sets the latitude of the currently selected site.",
        "command": ":St",
        "parameter": "{0:1s}{1:2d}*{2:2d}#",
        "return": "{0:1d}#",
    },
    "GetLongitude": {
        "description": "Gets the longitude of the currently selected site.",
        "command": ":Gg#",
        "parameter": None,
        "return": "{0:3d}*{1:2d}#",
    },
    "SetLongitude": {
        "description": "Sets the longitude of the currently selected site.",
        "command": ":Sg",
        "parameter": "{0:3d}*{1:2d}#",
        "return": "{0:1d}#",
    },
    "GetOffsetFromGreenwichMeanTime": {
        "description": "Gets the offset from Greenwich Mean Time.",
        "command": ":GG#",
        "parameter": None,
        "return": "{0:1s}{1:2d}#",
    },
    "SetOffsetFromGreenwichMeanTime": {
        "description": "Sets the offset from Greenwich Mean Time.",
        "command": ":SG",
        "parameter": "{0:1s}{1:2d}#",
        "return": "{0:1d}#",
    },
    "StartSlewInDirection": {
        "description": "Starts motion in the specified direction n,e,w and s at the current rate.",
        "command": ":M",
        "parameter": "{0:1s}#",
        "return": None,
    },
    "StopSlewInDirection": {
        "description": "Stops motion in the specified direction n,e,w and s at the current rate.",
        "command": ":Q",
        "parameter": "{0:1s}#",
        "return": None,
    },
    "SlewToTarget": {
        "description": "Slews telescope to current object coordinates. 0 is returned if the telescope can complete the slew, 1 is returned if the object is below the horizon, 2 is returned if the object is below the “higher” limit, and 4 is returned if the object is above the lower limit.",
        "command": ":MS#",
        "parameter": None,
        "return": "{0:1d}{2:s}#",
    },
    "AbortSlewToTarget": {
        "description": "Stops a slew to an object.",
        "command": ":Q#",
        "parameter": None,
        "return": None,
    },
    "SetMotionRate": {
        "description": "Sets the motion rate to guide (G), center (C), find (M), or slew (S).",
        "command": ":R",
        "parameter": "{0:1s}#",
        "return": None,
    },
    "SetMaxSlewRate": {
        "description": "Sets the maximum slew rate to “N” degrees per second where N is 2 through 4.",
        "command": ":Sw",
        "parameter": "{0:1s}#",
        "return": None,
    },
    "GetObjectRA": {
        "description": "Gets the object right ascension.",
        "command": ":Gr#",
        "parameter": None,
        "return": "{0:2d}:{1:2d}.{2:1d}#",
    },
    "SetObjectRA": {
        "description": "Sets the object right ascension.",
        "command": ":Sr",
        "parameter": "{0:2d}:{1:2d}.{2:1d}#",
        "return": "{0:1d}#",
    },
    "GetTargetDeclination": {
        "description": "Gets the object declination.",
        "command": ":Gd#",
        "parameter": None,
        "return": "{0:1s}{1:2d}*{2:2d}#",
    },
    "SetTargetDeclination": {
        "description": "Sets the object declination.",
        "command": ":Sd",
        "parameter": "{0:1s}{1:2d}*{2:2d}#",
        "return": "{0:1d}#",
    },
    "SyncCoordinates": {
        "description": "Syncs current telescope coordinates to the object coordinates and returns a string indicating which objects coordinates were used.",
        "command": ":CM#",
        "parameter": None,
        "return": "{0:s}",
    },
}
